### ISSUE TITLE
Push gem to gemcutter

### ISSUE THREAD

**Issue by erikdahlstrand** [stffn/declarative_authorization#10]
Please push the gem to gemcutter. It's a matter of
    gem push yourgem-0.0.1.gem

**Comment by stffn** [comment]
It now is at gemcutter

**Comment by timcharper** [comment]
hey, Steffen, not sure if you've seen this or not, but you can mark an issue is closed so it will no longer appear as open/unread.

**Comment by timcharper** [comment]
I'm retarded. Disregard.
