### ISSUE TITLE
Ruby 1.9.2 Rails 3.1

### ISSUE THREAD

**Issue by swistaczek** [stffn/declarative_authorization#102]
➜  bzdury2 git:(master) ✗ rails g
/usr/local/rvm/gems/ruby-1.9.2-p180/bundler/gems/rails-af1b48926f49/activerecord/lib/active_record/base.rb:1039:in `method_missing': undefined local variable or method`scopes' for ActiveRecord::Base:Class (NameError)
    from /usr/local/rvm/gems/ruby-1.9.2-p180/bundler/gems/declarative_authorization-27373691be91/lib/declarative_authorization/in_model.rb:37:in `block in included'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/bundler/gems/declarative_authorization-27373691be91/lib/declarative_authorization/in_model.rb:36:in`module_eval'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/bundler/gems/declarative_authorization-27373691be91/lib/declarative_authorization/in_model.rb:36:in `included'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/bundler/gems/declarative_authorization-27373691be91/lib/declarative_authorization.rb:17:in`include'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/bundler/gems/declarative_authorization-27373691be91/lib/declarative_authorization.rb:17:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.12/lib/bundler/runtime.rb:68:in`require'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.12/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.12/lib/bundler/runtime.rb:66:in`each'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.12/lib/bundler/runtime.rb:66:in `block in require'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.12/lib/bundler/runtime.rb:55:in`each'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.12/lib/bundler/runtime.rb:55:in `require'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.12/lib/bundler.rb:120:in`require'
    from /media/Dane/noweProjekty/bzdury2/config/application.rb:7:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/bundler/gems/rails-af1b48926f49/railties/lib/rails/commands.rb:20:in`require'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/bundler/gems/rails-af1b48926f49/railties/lib/rails/commands.rb:20:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

**Comment by jasonpgignac** [comment]
+1 - Identical issue. If you upgrade to the Rails 3.1 release candidate, and run rake, you receive this error.
