### ISSUE TITLE
Engine#flatten_roles and #flatten_privileges rely on undefined behavior

### ISSUE THREAD

**Issue by dudleyf** [stffn/declarative_authorization#108]
Authorization::Engine#flatten_roles (authorization.rb:315) and Authorization#flatten_privileges (authorization.rb:324) both modify  an array while iterating over it. According to http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/23633, the behavior of that kind of loop is undefined. Rubinius doesn't see the modifications to the array during the loop, and this causes those methods to return wrong values.

**Comment by stffn** [comment]
Thanks for pointing it out.
