### ISSUE TITLE
When using get_with receive deprecation warning

### ISSUE THREAD

**Issue by bhardin** [stffn/declarative_authorization#109]
I have a simple test using get_with in which I receive the following deprecation warning.

/Library/Ruby/Gems/1.8/gems/declarative_authorization-0.5.2/lib/declarative_authorization/maintenance.rb:188: warning: Object#id will be deprecated; use Object#object_id

Here is my test:

```
it "as authenticated user should be successful" do
get_with :user, :new
response.should be_success
end
```

Environment
Rails 3.0.5
declarative_authorization 0.5.2

**Comment by stffn** [comment]
The reason is that the first parameter to get_with should be a user object.  Symbol#id is indeed deprecated, not so AR::Base#id.
