### ISSUE TITLE
Can't install as plugin in Rails 3

### ISSUE THREAD

**Issue by marcgg** [stffn/declarative_authorization#111]
In the documentation : 

Alternatively, to install from github, execute in your application’s root directory
`cd vendor/plugins && git clone git://github.com/stffn/declarative_authorization.git`

This does not work for Rails 3 and returns: 

`declarative_authorization is a Railtie/Engine and cannot be installed as a plugin (RuntimeError)`

This seems to be linked to this: https://gist.github.com/af7e572c2dc973add221
Possible explanation in this blog post: http://www.litp.org/blog/?p=128

The poster found that "[he] was setting up my engine was not working as a plugin: Rails automatically reads plugins as engines, so when [he] was specifying an Engine class it was getting loading the engine twice."

Seen this bug with Rails 3.1.0rc6 but I'm sure it happens with any version of Rails 3.

Quick fixe: change the documentation ^^
Best fixe: Allow inclusion as a plugin by not defining decl_auth as an Engine when using Rails 3

**Comment by marcgg** [comment]
This seems related to Issue #44 as well

**Comment by stffn** [comment]
You are absolutely right.  We need to improve on the README.  For now, the quick fix.
