### ISSUE TITLE
No way to allow custom method to act like 'new'

### ISSUE THREAD

**Issue by cthielen** [stffn/declarative_authorization#113]
I use filter_resource_access on my controllers and have noticed, if I need to load a resource that isn't searched by ID (for instance, /user/their_name), I have to set a before_filter that loads the resource first. This seems to bypass declarative_authorization's resource loading.

But declarative_authorization seems to have a special convention for the 'new' method, as it doesn't load anything. I need to create a new-like method which also loads nothing but cannot get declarative_authorization to stop trying to find a params[:id].

Is there something in the design of declarative_authorization that would allow for this case?

**Comment by stffn** [comment]
Have you tried the appropriate parameters to filter_resource_access?  :additional_new etc.?  Also, this seems more like a usage questions, which better fit the mailing list.

**Comment by cthielen** [comment]
Hi stffn,

My apologies. It is a usage question really. Thanks for the pointer!
