### ISSUE TITLE
How to write this rule about tree structure

### ISSUE THREAD

**Issue by lzpddd** [stffn/declarative_authorization#117]
class User < ActiveRecord::Base
  blongs_to :organization
  has_many :roles, :through => :assignments
  ...
  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end
end

class Organization < ActiveRecord::Base
  acts_as_tree
  has_many :users
  has_many :loans
end

organization have below records:
id  name        parent_id
1   organ1  null
2   organ2  1 
3   organ2  2
4   organ2  2
5   organ2  3

 class Loan < ActiveRecord::Base
  belongs_to :organization
end   

I want to list all records in Loan where ancestor is current_user.organization.id

**Comment by stffn** [comment]
Please use the issue tracker for bugs and feature requests -- and turn to the mailing list for usage-related questions.

**Comment by lzpddd** [comment]
I have 3 models :User, Organization , Loan 
Organization is a rigid hierarchy(as tree), it has many root node(root node's field panent_id's value is null or 0), each root node has many children, each child has many children ...
User belongs to Organization (through field organization_id)
Loan belongs to Organization (through field organization_id) also

I want to find all records in model Loan action index that conditions are organization_id is equal current_user.organization_id and organization_id are equal current_user.organization.children node, querying result in last email

the issue are:
How to write the DSL in authorization_rules.rb ?
How to write attribute check?
