### ISSUE TITLE
Permission denied: No matching rules found for index

### ISSUE THREAD

**Issue by swistaczek** [stffn/declarative_authorization#119]
Hey guys,
Do you have problem with permissions on admin section? I logged in as user with admin role but d_a raises error.

Permission denied: No matching rules found for index for #<User id: 1, email: "test@asd.pl", encrypted_password: "$2a$10$70QdJiv1qfj7mScO44HhkO3TUNCI6W.kA3upXzHjwriO...", reset_password_token: nil, remember_token: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2011-11-29 19:59:14", last_sign_in_at: "2011-11-29 18:43:32", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", login: "admin", identity_url: nil, name: "", state: "active", twitter_token: nil, activated_at: nil, deleted_at: nil, created_at: "2011-11-26 23:24:01", updated_at: "2011-11-29 19:59:14", language: "pl"> (roles [:admin], privileges [:index], context :admin_dashboard).

Where my current_user:
ruby-1.9.2-p180 :006 > User.first.role_symbols
  User Load (0.3ms)  SELECT "users".\* FROM "users" LIMIT 1
  Role Load (0.2ms)  SELECT "roles".\* FROM "roles" INNER JOIN "roles_users" ON "roles"."id" = "roles_users"."role_id" WHERE "roles_users"."user_id" = 1
 => [:admin] 

This is auth rules:
authorization do
  role :admin do
    has_permission_on :authorization_rules, :to => :read

```
has_permission_on [
  :admin_commits,
  :admin_dashboard,
  :admin_settings,
  :admin_announcements,
  :admin_delayed_jobs,
  :admin_users
], :to => [:manage]

has_permission_on :admin_users, :to => [
  :active, :search,:pending,:reset_password,:suspended, :activate,
  :deleted, :suspend , :unsuspend, :purge, :toggle_role, :update
]
```

  end

  role :moderator do
    has_permission_on [
      :moderator_dashboard
    ], :to => [:manage]
  end
end

privileges do
  privilege :manage, :includes => [:create, :read, :update, :delete]
  privilege :read, :includes => [:show]
  privilege :create, :includes => :new
  privilege :update, :includes => :edit
  privilege :delete, :includes => :destroy
end

Admin base controller contains:
class Admin::BaseController < ApplicationController
  filter_access_to :all

**Comment by stffn** [comment]
Please direct these kind of usage questions to the mailing list and reserve the issue tracker for bugs and feature requests.

As for the problem: you might want to add :index back to the privileges that are included in :read (cf. the example rules file)
