### ISSUE TITLE
Again: Unnessecary db query in conjunction with named_scope

### ISSUE THREAD

**Issue by ledermann** [stffn/declarative_authorization#12]
With version 0.4 we have a bug like in issue #7 again:

MyModel.with_permissions_to(:read).foo_scope
=> One query, all is fine

MyModel.foo_scope.with_permissions_to(:read)
=> Two queries: The first for "MyModel.foo.find :all" (unnessecary), the second is the right one.

If you can't reproduce this, I will try to build a failing test or something.

**Comment by stffn** [comment]
Fixed another unnecessary query -- those AR proxies really are brittle.  Closed by 4ade8a47c889ff18411ec50b1c92b6df9e2b041d
