### ISSUE TITLE
Problems with attribute checks on a namespaced model

### ISSUE THREAD

**Issue by gravitystorm** [stffn/declarative_authorization#120]
I'm having problems with attribute checks on a namespaced model. Here is the relevant bits of the controller:

``` ruby
class Library::NotesController < ApplicationController
  before_filter :load_note, except: [:new, :create]
  filter_access_to :edit, attribute_check: true

  def edit
    permitted_to!(:edit, @note)
  end

  protected

  def load_note
    @note = Library::Note.find(params[:id])
  end
end
```

The `permitted_to!` is simply there to trigger exceptions so I can get a full framework trace.

I've tried multiple variations on the filter_access_to line, and none of them seem to work

**A)** `filter_access_to :edit, attribute_check: true`

This gives:
uninitialized constant Note (lib/declarative_authorization/in_controller.rb:639:in 'load_object')

@context is nil, so it's contr.class.controller_name.classify.constantize . But `Library::NotesController.controller_name` is "notes", so `"Note".constantize` fails.

**B)** `filter_access_to :edit, attribute_check: true, model: Library::Note`

This gives:
'@library/note' is not allowed as an instance variable name (lib/declarative_authorization/in_controller.rb:641:in 'instance_variable_get')

This is because "Library::Note".underscore returns "library/note" as per
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/methods.rb#L76

**C)** `filter_access_to :edit, attribute_check: true, load_method: :load_note`

This loads the model fine, but still doesn't work:
No matching rules found for edit for #<User id: 2> (roles [:admin, :member, :guest], privileges [:edit, :manage], context :"library/notes")
The context here has a forward slash, but the context should be underscore separated.

I suspect this is lib/declarative_authorization/authorization.rb#L165 which calls tableize on the object's class name, which is found at
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/methods.rb#L122
and also calls underscore, as in part B.

For reference, Our authorization rules include

``` ruby
has_permission_on :library_notes, to: [:index, :new, :create, :show]
has_permission_on :library_notes do
  to [:edit]
  if_attribute created_by: is { user }
end
```

The first section works fine, it's only the edit method guarded by the if_attribute that we're having problems with.

If we're approaching this in the wrong manner, then please point me in the right direction! Otherwise, I think there are perhaps 3 separate bugs with using namespaced models in attribute_check situations.

**Comment by DanKnox** [comment]
Declarative auth definitely does not work well with namespaces.

I know this isn't exactly a fix but it is a work around that I have implemented on my project. Ditch the `library_notes` and instead set the context explicitly.

In your model: `using_access_control :context => :notes`
In your controller: `filter_access_to :edit, attribute_check :true, load_method: :load_note, :context => :notes`
In your rules: `has_permission_on :notes`

**Comment by maletor** [comment]
This is a problem.

**Comment by stffn** [comment]
I'd suggest DanKnox' approach: explicitly set the :context parameter, both for using_access_control and for filter_access_to.

Second option: define the Model.decl_auth_context method. Then, you control what the context for the model is (should make option B work).

**Comment by bluebird-communication** [comment]
Why this issues has been closed ? This is definitively not the way to make declarative_authorization more compliant with Rails and stable in long term.
