### ISSUE TITLE
Authorization.ignore_access_control  +  Production mode  =  :(

### ISSUE THREAD

**Issue by DanKnox** [stffn/declarative_authorization#121]
My application is experiencing an issue that only crops up after being in production mode for a few days. At this point in time, requests that are working fine suddenly begin redirecting with access denied.

This is happening on a restful API that is exposed to third parties. For the API, we disable access control using `Authorization.ignore_access_control(true)` in a before filter and `Authorization.ignore_access_control(false)` in an after filter. Is there something obviously wrong with doing this that I am missing?

Any help is appreciated.

**Comment by stffn** [comment]
It should work, ignore_access_control is Thread-safe.  Still, it's actually rather thought to be used in exceptional cases.  In this case, I'd go for having an API user that has a role with the appropriate permissions.

**Comment by DanKnox** [comment]
In what context are you using "thread safe"? I just tested and it looks as
though disabling access control through this method and not re-enabling it
causes site wide changes for separate sessions.

**Comment by stffn** [comment]
In the same way as setting I18n.locale is thread safe: if there are parallel threads running your app, setting it will be global only for the current thread.  This does not imply anything for the following request, though.
