### ISSUE TITLE
filter_access_permissions just gets bigger

### ISSUE THREAD

**Issue by bonds** [stffn/declarative_authorization#123]
I put a breakpoint in lib/declarative_authorization/in_controller.rb around line 301 and I noticed that filter_access_permissions.size grows by 1 with every request. I'm not that familiar with DA's code as yet, but that seems fishy, I thought I'd mention it in case it may be of interest.

**Comment by stffn** [comment]
This is in development, right?  It does remove any conflicting earlier definitions here.  As you observed in #124, this does not help with changes to the filter_access_to statements.  However, since we don't know whether it is the first call to filter_access_to (or filter_resource_access), we cannot just wipe out all existing filters in filter_access_permissions.  Any ideas?

**Comment by bonds** [comment]
Yes, in development. 

I tried switching from using a class variable to an instance variable for storing permissions and that _seems_ to work (and it seems to fix issues #123 and #124) , but I wasn't able to get the tests working (I'm running Rails 3.1 and Ruby 1.9.3 not sure if those are causing problems) so this is a bit of a shot in the dark: https://github.com/bonds/declarative_authorization/commit/2439ff4d8387fd301b11e42391df49b4f6125d8e

**Comment by stffn** [comment]
The code is called outside of the context of a concrete controller instance.  What kind of instance variable is it then?  Also, we do not want those variables to be cleared on each request in production, just that they are cleared on class reload in development.

We should probably also have a look how Rails handles this kind of problem.  Do they explicitly erase class variable state on class reload?

**Comment by bonds** [comment]
They are being set as class instance variables, so they reset when the class reloads I think. Putting a debugger line in there, I notice they are not resetting with each request, so I'm not sure why its working.

**Comment by stffn** [comment]
There surely is some research needed here.  Until then, we need to live with the fact that in development, we might need to restart the server every once in a while to reflect changes to filter_resource_access/filter_access_to statements.

**Comment by bonds** [comment]
This is pretty old, assuming its a wontfix and closing.
