### ISSUE TITLE
changing filter_access_to actions requires a restart to take effect

### ISSUE THREAD

**Issue by bonds** [stffn/declarative_authorization#124]
repro steps:

start with filter_access_to :all on your (CRUD-like) controller
load your :show page and you see an unauthorized error as you expect
change to filter_access_to :index
load your :show page and you _still_ get an unauthorized error, even though you aren't filtering the :show action anymore
restart your web server
load your :show page and now you see it (no error this time)

expected:

refreshing the page after a filter_access change is all that is necessary to see the effect, it is not necessary to restart the server to see the effect

**Comment by stffn** [comment]
Should be tracked in #123
