### ISSUE TITLE
filter_access_to :all vs. filter_resource_access

### ISSUE THREAD

**Issue by cthielen** [stffn/declarative_authorization#131]
When I use filter_resource_access, I receive a NameError warning but when I switch it to simply say filter_access_to :all, I do not receive this error.

Is this expected behavior, or should I post some code demonstrating it?

Sorry for the brevity - not sure if I'm the one doing something wrong.

**Comment by cthielen** [comment]
I should note this is Rails 3.2.1 and Ruby 1.9.3p0.

**Comment by kristallizer** [comment]
@cthielen 

Strange. I am using the same versions of Ruby/RoR you are using, and `filter_resource_access` seems to be working fine for me. Can you elaborate a bit on the error you are getting?

**Comment by cthielen** [comment]
I cannot reproduce the issue. Consider the issue closed. I'll re-open it if I encounter it again.

For clarity: are filter_resource_access and filter_access_to :all equivalent statements?

**Comment by stffn** [comment]
@nslocum Maybe the documentation is unclear there:  You can use filter_resource_access with non-standard actions, you only have to specify how they should be handled -- that is, as collection, member, etc.  See e.g. the additional_member parameter.

@cthielen No, filter_resource_access is a more sophisticated (high-level) API than filter_access_to.  The former sets up filter_access_to rules in the background.
