### ISSUE TITLE
Serialize value bypass authorization

### ISSUE THREAD

**Issue by jeromelefeuvre** [stffn/declarative_authorization#132]
Hi,

I hope it's me but I have  serialize field (serialize :point_of_sale_ids, Array). 

When I add an authorization on this field and test it. Authorization is bypassed and I can updated this field.

Thanks for the feedback

Jerome

**Comment by stffn** [comment]
Please expand a bit. Can you provide the rules you are using?  Serialized values will certainly not work for query rewriting (with_permissions_to), but should work in filter rules for the controller and for permitted_to? etc.
