### ISSUE TITLE
tighter/narrower function call on attribute check

### ISSUE THREAD

**Issue by badeball** [stffn/declarative_authorization#133]
Hey,

I'm having a little bit trouble explaining this, so let me give a brief introduction to my application and what I am trying to accomplish. I have a member model and a role model. A member can have several roles and a role can have several members. (Creating a MembersRole helper model)

Each role has a 'passable' boolean attribute, which means that a user with that role can pass it along to another user. This is implemented in the following way in authorization_rules.rb.

``` ruby
authorization do
  Role.all.each do |role|
    if role.passable
      role role.title.to_sym do
        has_permission_on :roles, :to => :pass do
          if_attribute :id => is { role.id }
        end
      end
    end
  end
end
```

In the roles controller one will find something along the way of the following.

``` ruby
filter_access_to :pass, :attribute_check => true
```

We utilize TDD in this project and since dec_auth calls 'find', (lib/declarative_authorization/in_controller.rb:644) we need to mock that call.

``` ruby
describe RolesController do
  describe :pass do
    before(:each) do
      @role = mock_model(Role)
      Role.stub(:find).and_return(@role)

      # ...

    end
  end
end
```

However, the call to 'all' in authorization_rules.rb seem to utilize 'find' internally, and 'all' will return that single role object. Trying to call 'each' on that single object obviously results in an error. After some debugging, I came to the conclusion that the problem may be fixed entirely by modifying lib/declarative_authorization/in_controller.rb:644 from

``` ruby
object = load_object_model.find(contr.params[:id])
```

... to

``` ruby
object = load_object_model.find_by_id(contr.params[:id])
```

So, how can we make this happen? (Oh, and yeah - I'm new to Github)

**Comment by stffn** [comment]
Wow, never had dynamic roles, looks interesting...  Wouldn't it help to mock find_by_id instead of find?  Rails should be using that internally as well.

**Comment by stffn** [comment]
This really is a usage-related request, which should rather go to the mailing list.
