### ISSUE TITLE
Documentation Error - Adding additional Authorization Files incorrect constant name

### ISSUE THREAD

**Issue by mhefferan** [stffn/declarative_authorization#139]
in README under Authorization Rules headding the following line 

Authorization rules are defined in config/authorization_rules.rb (Or redefine rules files path via +Authorization::AUTH_RULE_FILES+). E.g.

Should Read::

Authorization rules are defined in config/authorization_rules.rb (Or redefine rules files path via +Authorization::AUTH_DSL_RULES+). E.g.

**Comment by stffn** [comment]
Actually, AUTH_DSL_FILES :) Thanks anyways!
