### ISSUE TITLE
Update permissions are only checked the first time

### ISSUE THREAD

**Issue by rkistner** [stffn/declarative_authorization#14]
Update permissions are only checked on the first save. If this is the intended behavior, it should be clear in the documentation.

```
post = Post.first
post.owner_id = 2
post.save
# Invalid update, exception is thrown

post = Post.first
post.contents = "..."
post.save
# Valid update, no exception thrown

post.owner_id = 2
post.save
# Invalid update, but no exception is thrown
```

**Comment by seivan** [comment]
Why would this be an intended behavior, sounds like a serious issue.

**Comment by stffn** [comment]
I just tried to reproduce this behavior, but couldn't.  First changing an unrelated attribute doesn't let me change the critical one.  I push the reorganized tests in a second to github.

**Comment by rkistner** [comment]
I'll run the tests when I'm back at my office (next year probably)

**Comment by rkistner** [comment]
It seems to be a problem with my own code then: even the validations are not run again after the first save. Still no idea what is causing it.
