### ISSUE TITLE
warning: already initialized constant AUTH_DSL_FILES

### ISSUE THREAD

**Issue by chrisgaunt** [stffn/declarative_authorization#141]
I've put `Authorization::AUTH_DSL_FILES = [MyEngine::Engine.root.join("config", "authorization_rules.rb").to_s]` into an initializer and when I start up the app in development or production mode I get `...config/initializers/declarative_authorization.rb:1: warning: already initialized constant AUTH_DSL_FILES`

For some background: This initializer is in a gem (a rails engine), which is our CMS system. declarative_authorization is required as part of the gem. This gem is then used in other apps. I am seeing the error when running the gems specs as well as when running the other apps in development or production env.

Any idea why?

**Comment by stffn** [comment]
The reason is that we still don't have a proper configuration system (see #44).  So, the warning is correct, we just need a better way of setting this variable.

**Comment by chrisgaunt** [comment]
Thanks for the response. I'll keep an eye on #44

**Comment by house9** [comment]
if you get tired of seeing the warning - wrap the code in `silence_warnings` block - see http://stackoverflow.com/questions/6890939/suppress-particular-warning-in-ruby

I am setting AUTH_DSL_FILES in application.rb and the `silence_warnings` method is available

```
silence_warnings do
  Authorization::AUTH_DSL_FILES = [
    "#{Rails.root}/config/auth/foo.rb",
    "#{Rails.root}/config/auth/bar.rb"
  ]
end
```

seems a good workaround
