### ISSUE TITLE
if_attribute doesn't work with multiple hash

### ISSUE THREAD

**Issue by ludovicjamet** [stffn/declarative_authorization#159]
I use declarative_authorization on Ruby on rails 3.1.

The context : a group has many albums (groupalbum), a group is own by one user (user_id in foreign key for group table).
Only the owner of the group can create albums.

Here is my authorization_rules.rb :

```
has_permission_on [:group_albums], :to => [:adding] do
    if_attribute :group =>  { :user => is { user } }
end
```

Here is my GroupAlbumsControler :

```
class GroupAlbumsController < ApplicationController
    before_filter :set_group_album_from_params, :only => :show
    before_filter :set_group_album_new, :only => [:index, :new]
    filter_access_to :all, :attribute_check => true
    (...)
end
```

But it doesn't work :

```
You are not allowed to access this action.
```

Even if I'm logged in with the owner of the group.

Where is my mistake ? Is it a bug ?

**Comment by stffn** [comment]
My first guess is that this is a usage problem that should be discussed on the mailing list. Generally, this should work. Can you check the logs for more details on the denied access and report it on the mailing list?
