### ISSUE TITLE
Use with ActionController::Metal

### ISSUE THREAD

**Issue by maletor** [stffn/declarative_authorization#169]
Would be nice if you could just drop in   

``` ruby
include Authorization::AuthorizationInController
include ActionController::HideActions
```

to get declarative_authorization rolling with `ActionController::Metal`. Unfortunately, the use of `logger` and not `Rails.logger` prevents this and one has to override.

``` ruby
def logger
  Rails.logger
```

**Comment by stffn** [comment]
So you argue to have this included generally? Can you provide a pull request?

**Comment by maletor** [comment]
Yes.
