### ISSUE TITLE
attribute check is done on array instead of the instances in the array

### ISSUE THREAD

**Issue by ghost** [stffn/declarative_authorization#17]
If you have a has_many :through relationship as follows: 
_(taken from http://github.com/stffn/decl_auth_demo_app)_

<code>**conference** <1------\*> **conference_attendees** <*--------1> **user**</code>

```
class Conference < ActiveRecord::Base
  has_many :conference_attendees
  has_many :attendees, :through => :conference_attendees, :source => :user
```

If you want to give read for a conference to all users attending that conference you would type

```
has_permission_on :conferences, :to => :read do
  if_attribute :attendees =>  contains {user}
end
```

That works fine. But what if you have a **attribute** on the **conference_attendees** model that you **need to consider** as well. Perhaps you wan't to **give read** right to **all users** attending a conference and that **have paid** _(paid beeing a boolean in the conference_attendees model)_. 

```
has_permission_on :conferences, :to => :read do
  if_attribute :conference_attendees =>  {:user => is {user}, :paid => true}
end
```

This will work when using <code>Conference.with_permissions_to(:read)</code> but will fail if <code>:attribute_check => true</code>
### To replicate this error:
1. In your **decl_auth_demo_app** change **authorization_rules.rb** line 4 from <code>if_attribute :published => true</code>  
   to  
   <code>if_attribute :conference_attendees => {:user => is{user}}</code>
2. Go to  **/conferences** as **presenter_2**
3. You will see conference **Emerging Technologies 2009**
4. Click on the conference and you will get _"You are not allowed to access this action."_
   
   ```
   Permission denied: Error when calling user on [#<ConferenceAttendee id: 15, user_id: 3, conference_id: 2>] for validating attribute: undefined method `user' for [#<ConferenceAttendee id: 15, user_id: 3, conference_id: 2>]:Array
   Filter chain halted as [:filter_access_filter] rendered_or_redirected.
   ```

**Comment by xtreme** [comment]
I now see that you have fixed this in your commit http://github.com/stffn/declarative_authorization/commit/907255af13a710b4683ee8ce86acf95977a53860.
