### ISSUE TITLE
/authorization_rules no method error - Rails 3.2.11

### ISSUE THREAD

**Issue by glarrai1** [stffn/declarative_authorization#174]
NoMethodError in Authorization_rules#index

Showing /home/redvel2/.rvm/gems/ruby-1.9.3-p374@tsp/gems/declarative_authorization-0.5.7/app/views/authorization_rules/index.html.erb where line #16 raised:

undefined method `shift' for :authorization_rules:Symbol

Extracted source (around line #16):

16: <%= policy_analysis_hints(syntax_highlight(h(@auth_rules_script)), @auth_rules_script) %>

**Comment by viacommits** [comment]
See #185 and zeiv/declarative_authorization@1c94e4f1ecadfefbec94ecc3ce53a41e7183d6c6
