### ISSUE TITLE
Authorization::Maintenance::without_access_control can not be nested

### ISSUE THREAD

**Issue by ledermann** [stffn/declarative_authorization#2]
It's not possible to do nesting like this:

<pre>
Authorization::Maintenance::without_access_control do
  do_something
  Authorization::Maintenance::without_access_control do
    do_something
  end
  do_something # => here the access control takes place again!
end
</pre>

**Comment by stffn** [comment]
Fixed.

**Comment by ledermann** [comment]
The fix works fine, thank you!
