### ISSUE TITLE
request_with methods ignore given user 

### ISSUE THREAD

**Issue by tom-kuca** [stffn/declarative_authorization#20]
I just start with automatic testing and found a problem with authorization plugin. The request_with methods, like get_with, put_with etc., ignore given user and consider all requests to be sent by a guest.
## Example

I restrict access to index of articles only for admin: 

```
# config/authorization_rules.rb
authorization do
  role :admin do
    has_permission_on :articles, :to => :index
  end
end
```

add 'filter_recourse_access' to the articles controller and and then make a simple test: 

```
# test/functional/articles_controller_test.rb
require 'test_helper'

class ArticlesControllerTest < ActionController::TestCase

  test "should get index" do
    with_user(admin) do 
      should_be_allowed_to :index, :articles # OK 
    end
    get_with admin, :index
    assert_response :success  # failed - Expected response to be a <:success>, but was <403>
  end

end
```

The last assert fails - the page should be rendered, but the response status is :forbidden. If I do it manually (launch server, login as admin and view page), it works well - the page is shown. Log file for test (log/test.log) shows that there was a request for the page and the user was a guest:

```
Processing ArticlesController#index (for 0.0.0.0 at 2009-12-23 18:49:46) [GET]
    Parameters: {"action"=>"index", "controller"=>"articles"}
Permission denied: No matching rules found for index for #<Authorization::GuestUser:0xb66ffa34 @role_symbols=[:guest]> (roles [:guest], privileges [:index, :read, :manage], context :articles).
Filter chain halted as [:filter_access_filter] rendered_or_redirected.
Completed in 9ms (View: 1, DB: 12) | 403 Forbidden [http://test.host/articles]
```
## Where it goes wrong?

Let's take a look at the request with method.

```
# File lib/declarative_authorization/maintenance.rb, line 156
def request_with (user, method, xhr, action, params = {}, 
    session = {}, flash = {})
  session = session.merge({:user => user, :user_id => user.id}) # creates session[:user]
  with_user(user) do                                  # assigns Authorization.current_user = admin 
    if xhr
      xhr method, action, params, session, flash
    else
      send method, action, params, session, flash     # assigns Authorization.current_user = nil and performs the request 
    end
  end
end
```

First it creates a session with given user, then it assigns admin as current user. So far so good. Then it performs a request which activates filters in application controller, namely the :set_current_user before_filter. The method I'm using doesn't take care of session[:user], it uses its own method for determining the current user. It doesn't find any current user and assigns nil to Authorization.current_user, which is later replaced by a default GuestUser.

```
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_current_user

  def current_user
    # find the current user, I'm using authlogic here
    UserSession.find.record 
  end

  def set_current_user
      Authorization.current_user = current_user 
  end
  ...
end
```
## Workaround

If I add sesson[:user] to the before filter in my application controller, the test pass without any failure as expected. 

```
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ...
  def set_current_user
      Authorization.current_user = current_user || session[:user]
  end
  ...
end
```

I believe this is a bug, at least there should be a notice in documentation about this behavior. I can provide any further information if needed or maybe even a patch. But I'm still a junior developer and I'm not sure whether my solution would be the correct one.

**Comment by stffn** [comment]
You are right, the request_with methods are very dependent on the way you set the user in the session.  This isn't a bug, though, only missing documentation.

Still: what would be a more general way of setting the user for functional testing in your opinion?
