### ISSUE TITLE
Make it possible to pass in instance variables

### ISSUE THREAD

**Issue by omarvelous** [stffn/declarative_authorization#21]
In the process of converting my App to integrate DA, great plugin so far... My only qualms are the fact that DA insists on creating the Instance Variables for the controllers... In a simple Rails app would be fine... However in more complex ones can cause added complexity... Especially when using plugins like Inherited Resources... I propose 2 solutions... Either expect the collection or resource be declared already, or add/integrate collection and resource options on filter_resource_access to pass in the collection and resource names to look for... Or even maybe ability to integrate it into the actions, and text after variable creation.

I think this gives you maximum flexibility. LMK what you think?

**Comment by stffn** [comment]
I think the default behavior is fine.  If there is the need to name the instance variable differently, we should have an option for that.  If you deem it necessary, patches are very welcome.

Which variable names would you like to customize, apart from the object instance variable?

**Comment by omarvelous** [comment]
Well for example Name Spaced controllers... Can't figure out how to accommodate for those. Another issue is with Inherited Resources, I can restfully create a Polymorphic controller (ie. Comments) that can accomodate multiple Parents (ie. User, Post, Topic, etc.)... The rule I can setup... however the "filter_resource_access" is where the issue lies... What exactly, i'm still trying to track it down. But :nested_in can't accommodate multiple models. Solution would be to create multiple controllers using :context option, if I'm not mistaken...

**Comment by stffn** [comment]
I'm not sure how all these issues relate to instance variable names.

For usage discussions, please refer to the mailing list first.

**Comment by omarvelous** [comment]
I will do... Thanks... closing this for now. In the case of the name spaced controllers having a Forums controller and a Forums::Posts controller which refers to a Posts controller (Which is also used by a maybe Blogs::Posts controller) It doesn't seem to accomodate that. I've used "context" which seems to be the option for that to no avail.  Will post to mailing list.

Thanks

**Comment by omarvelous** [comment]
UPDATE: Spoke too soon... I found my issue, context is working now...
