### ISSUE TITLE
Problem to configure access rules

### ISSUE THREAD

**Issue by alec-c4** [stffn/declarative_authorization#23]
Hi,
could you tell me plz - how to write access rules for following scheme. I have 2 models - Post and Comment. Post has many comments and Comment belongs to Post. In posts_controller i have methods add_comment and remove_comment. But rules like 

```
    has_permission_on :posts, :to => :comments_manage do
      if_attribute :user_id => is {current_user}
    end
```

not working and

```
    has_permission_on :comments, :to => :comments_manage do
      if_attribute :user_id => is {current_user}
    end
```

not working too :(
additional information on privileges:

```
  privilege :comments_manage do
    includes :add_comment, :remove_comment
  end
```

**Comment by stffn** [comment]
Please use the issue tracker for feature requests and bug reports only. For usage questions, please post on the mailing list.
