### ISSUE TITLE
no way to prevent load_object from being executed

### ISSUE THREAD

**Issue by lwille** [stffn/declarative_authorization#24]
I'd like to have an option for filter_resource_access to toggle for which actions I don't like the "default" load_object to be executed (like the attribute_check switch).

In my ArticlesController, I have a search action which doesn't uses params[:id] to make a simple database lookup, but uses params[:searchterm] to search via Sphinx Search.
So I always got the error "ActiveRecord::RecordNotFound (Couldn't find Article without an ID)", because load_object tried to find a record with the ID equal to a text term :-)

Setting failed_auto_loading_is_not_found and attribute_check on filter_access_to didn't change anything.
After moving to declarative_authorization, it took me a time to find the following workaround:

```
class ArticlesController < ApplicationController
  before_filter :fake_article, :only=>:search
  filter_resource_access

  def search 
  # Search using Sphinx Search
    @articles = Article.search params[:searchterm]
  end
# ...
  protected
    def fake_article
    logger.debug "Creating fake article."
    @article = Article.new
  end
```

**Comment by stffn** [comment]
Does the :additional_collection parameter for filter_resource_access solve your problem?
http://www.tzi.org/~sbartsch/declarative_authorization/master/classes/Authorization/AuthorizationInController/ClassMethods.html

**Comment by lwille** [comment]
Don't know why, but with
      filter_resource_access :additional_collection=>:search
everything works :-)

Thanks!

Thanks :-)

**Comment by lwille** [comment]
Unfortunately, the proposed solution only worked for this specific action.

How is the default object preloading handled in a normal create action, where no ID parameter is supplied? I'm not getting any useful info, neither from documentation nor source code, as the plugin seems to behave completely different.

What was the initial motivation for doing such preloading, as I am having so much trouble with it - I just had the idea of forking your project and throw away everything that is not authorization-related, but I don't have the time to do so. This seems much more complicated than it should be.

Sorry for these harsh words, but as long as I have to pollute my code with nasty before_filtered @fake_instances just to get the plugin working ...

Kind regards

Leonhardt

**Comment by stffn** [comment]
Preloading is, in fact, necessary for authorization.  It provides the object to authorize against.  Most RESTful actions have these objects as identified by params[:id].  Of course, there are some actions that don't act on single objects, those are typically called collections in Rails.

The other exception are new/create actions.  As the documentation says, for new and create a new object is instantiated from params[:object_name].

**Comment by stffn** [comment]
As an aside: for this type of usage questions, please turn to the mailing list as this is neither a bug report nor a feature request.
