### ISSUE TITLE
Bug using pluralize on contr.class.controller_name in file "in_controller.rb"

### ISSUE THREAD

**Issue by turgu1** [stffn/declarative_authorization#25]
First: thanks for this marvelous gem!!

Using pluralize on a controller_name that is already in its pluralized version is not a problem, unless it is a special word like "people":

When you do "organisations".pluralize, you get "organisations"
When you do "people".pluralize, you get "peoples"

The workaround would be to call singularize, then pluralize. So in file "in_controller.rb", I changed the following line:

```
  context = @context || contr.class.controller_name.pluralize.to_sym
```

to the following

```
  context = @context || contr.class.controller_name.singularize.pluralize.to_sym
```

This seems to resolve the problem.

**Comment by Odaeus** [comment]
I think you should be able to fix this by adding custom inflection rules in Rails' inflections initializer.

**Comment by turgu1** [comment]
Ruby already known about "person" and "people" in its standard inflection rules. It seems to be a problem with the pluralize method that can't take care of irregular words when they are supplied with their already plural version...

**Comment by Odaeus** [comment]
As far as I can tell the pluralizer does check:
    >> "cows".pluralize
    => "cows"

And the workaround for people would be:
    ActiveSupport::Inflector.inflections do |inflect|
      inflect.uncountable 'people'
    end

```
>> "people".pluralize
=> "people"
```

**Comment by turgu1** [comment]
Yep, but you can't singularize it anymore.

**Comment by Odaeus** [comment]
Ah I see, so the inflector re-pluralizes irregular inflections, which is probably correct behaviour ("peoples" is a word). But doing .singularize.pluralize seems a bit inelegant and probably slow (but I haven't benchmarked). Unfortunately I can't think of another solution that doesn't involve adding inflector workarounds.

**Comment by turgu1** [comment]
I've looked at the problem and it's effectively not easy. A fix could comes from rails itself, but then it would hurt every call to it (and it's called quite often...), checking irregular words every time before pluralizing a word.

It's especially annoying as the scaffolding convention make a controller name the pluralize version of the model associated to it. So that is why I have a model named "Person", its controller named PeopleController...

**Comment by stffn** [comment]
You can, of course, override the context with the :context parameter in filter_access_to and filter_resource_access.

Still, this issue should be solved by now.  Which version are you using?

**Comment by turgu1** [comment]
I can't find the version number as it doesn't appears anywhere in the code (it was installed as a plugin, not a gem). I'm not the one who imported it in the application and I suspect that it must be dated around November 2009.

I realize that the code has been changed significantly since then. I apologize to not having looked at the current release... Hope to do some tests with it to ensure everything is OK now.

**Comment by turgu1** [comment]
I've been able to do some test with the last release and everything seems ok now.

Thanks!!!
