### ISSUE TITLE
Permission denied: User.roles doesn't return an Array of Symbols

### ISSUE THREAD

**Issue by badnaam** [stffn/declarative_authorization#27]
User and Role model association has_many with :through option.

I am also using auth logic. created 2 roles admin and contributor. assigned permission to both roles as well as guest. Guest has no problem but when either user logs in they get no access error. 

here is the rules file

authorization do
    role :admin do
        includes :guest
        has_permission_on [:users, :roles, :articles, :home, :user_sessions], :to =>[:index, :show, :new, :create, :update, :destroy, :edit]
    end

```
role :guest do
    has_permission_on [:articles, :comments, :home, :roles,:users], :to => [:index, :show, :create, :new, :update, :edit]
end
role :contributor do

    has_permission_on [:articles, :users, :home], :to =>[:index, :show, :create, :new, :update, :edit]

end
```

end

Here is my role_symbols method
# for declarative_auth

def role_symbols
    #    roles.map do |role|
    #        role.name.underscore.to_sym
    #    end
    (self.roles || []).map {|r| r.name.to_sym}

end

Error in the logs
Processing HomeController#index (for 127.0.0.1 at 2010-02-07 00:02:05) [GET]
  [4;36;1mUser Columns (0.0ms)[0m   [0;1mSHOW FIELDS FROM `users`[0m
  [4;35;1mUser Load (0.0ms)[0m   [0mSELECT \* FROM `users` WHERE (`users`.`id` = '24') LIMIT 1[0m
  [4;36;1mSQL (0.0ms)[0m   [0;1mBEGIN[0m
  [4;35;1mUser Update (0.0ms)[0m   [0mUPDATE `users` SET `perishable_token` = 'QxUlovcyJAkEjy7kHCfO', `updated_at` = '2010-02-07 08:02:05', `last_request_at` = '2010-02-07 08:02:05' WHERE `id` = 24[0m
  [4;36;1mUser Load (0.0ms)[0m   [0;1mSELECT \* FROM `users` WHERE (`users`.`id` = 24) [0m
  [4;35;1mSQL (63.0ms)[0m   [0mCOMMIT[0m
The use of user.roles is deprecated.  Please add a method role_symbols to your User model.
  [4;36;1mRole Load (0.0ms)[0m   [0;1mSELECT `roles`.\* FROM `roles` INNER JOIN `assignments` ON `roles`.id = `assignments`.role_id WHERE ((`assignments`.user_id = 24)) [0m
  [4;35;1mRole Columns (0.0ms)[0m   [0mSHOW FIELDS FROM `roles`[0m
Permission denied: User.roles doesn't return an Array of Symbols ([#<Role id: 7, name: "admin", created_at: "2010-02-07 03:09:07", updated_at: "2010-02-07 03:09:07">])
Filter chain halted as [:filter_access_filter] rendered_or_redirected.
Completed in 172ms (View: 16, DB: 63) | 403 Forbidden [http://localhost/]

**Comment by stffn** [comment]
Please check that your user objects really responds to role_symbols.  That's what the errors say.

**Comment by badnaam** [comment]
Thanks for the response. Turns out my role_symbol method was in a private block, my bad!

Thanks for this great gem!!
