### ISSUE TITLE
filter_resource_access interferes with to_param

### ISSUE THREAD

**Issue by brandensilva** [stffn/declarative_authorization#28]
I'm able to get this working correctly with: 

def to_param
  "#{id}-#{name}"
end

Because it defaults to the ID but when I just want the name and make the necessary changes within the application, it does not work until I remove filter_resource_access. I'm sure this is because filter_resource_access assumes is using "find(params[:id])" rather than "find_by_name(params[:id])"

Is there any way to fix this or find a workaround?

**Comment by stffn** [comment]
Sure.  As the documentation says, you may provide custom load methods. 
See: http://www.tzi.org/~sbartsch/declarative_authorization/master/classes/Authorization/AuthorizationInController/ClassMethods.html

This question is more of a usage problem type.  Please use the mailing list for this type of questions and the issue tracker for bug reports and feature requests.
