### ISSUE TITLE
Any plans for Rails 3.0 support 

### ISSUE THREAD

**Issue by tricomsol** [stffn/declarative_authorization#31]
It would be very much helpful if decalartive authorization also have rails 3.0 support, because i tried it with rails 3.0 and ran into problems, i think those are mainly because of the changes in the Named scopes for ActiveRecords which returns a relation and Callbacks. Would love to see we Rails 3.0 support implemented sooner

**Comment by stffn** [comment]
You are right, the changes related to Arel cause the most problems.  That is fixed in my private branch by now.  I still need to clean it up and integrate Rails 2.x support back in, though.

**Comment by tricomsol** [comment]
Thanks very much, waiting eagerly to get my hands on that :)

**Comment by stffn** [comment]
There is now Rails 3 support on the master branch and a corresponding rails3 branch for the demo app.  Please report any remaining issues.

**Comment by krishna-shilpakar** [comment]
Thanks for it. But I was eager to know if declarative authorization works with MongoDB or not?

**Comment by stffn** [comment]
How does this fit here?  You could search the mailing list or ask there.  I have no experience with that.
