### ISSUE TITLE
tests don't run if RAILS_VERSION not provided

### ISSUE THREAD

**Issue by timcharper** [stffn/declarative_authorization#34]
See here:

http://github.com/stffn/declarative_authorization/blob/f2aa048/test/test_helper.rb#L21-26

nil is not a valid version requirement on my version of rubygems, and it breaks.

See this patch for the fix :)

http://github.com/timcharper/declarative_authorization/commit/5df55e59c1ea84802162c992d971aa59a30847d7

**Comment by stffn** [comment]
Fixed in 5df55e59c1ea84802162c992d971aa59a30847d7
