### ISSUE TITLE
feature request: omnipotent permissions 

### ISSUE THREAD

**Issue by timcharper** [stffn/declarative_authorization#35]
I find myself wanting to be able to add a role that has access to everything without me having to specifically permit him. Do you think this is bad design? Not needed?

**Comment by timcharper** [comment]
I have implemented it here: 

http://github.com/timcharper/declarative_authorization/commit/bae627fb4edc80d8212283e75e674d82b407fef4

**Comment by stffn** [comment]
Thanks for the patch.  I really don't know if this is bad design, personally, I wouldn't use it.  I'm not seeing any reasons to _not_ include it, though.

**Comment by timcharper** [comment]
after thinking about it a while longer, I'm not entirely sure if it is a good design decision. I recommend not pulling my patch :-)

Let me think about it for a while longer and see if I can come up with a really good reason why to include it. I don't want to contribute to feature bloat in your project.

**Comment by stffn** [comment]
You are not the first one to request this feature.  I wouldn't have implemented it, but given the clean patch and only minimal code footprint, I'd say it is worth it.

**Comment by timcharper** [comment]
okay, if others are reaching for it, I guess it might be justified. Would you like me to add a note in the readme as well?

**Comment by stffn** [comment]
No, I just pulled it already to a local branch and added some documentation.  I'll push it soon to github.

**Comment by stffn** [comment]
fixed in 4ecb402f1c7b24855db57933bfc5741d30c66a8f
