### ISSUE TITLE
test failure: test_removing_permission_adding_role fails

### ISSUE THREAD

**Issue by timcharper** [stffn/declarative_authorization#36]
it seems that it was broken by this commit:

http://github.com/stffn/declarative_authorization/commit/0e8d55c16c2197c89c2f57d6346d4023e7e61f7b

Using Ruby 1.8.6

**Comment by stffn** [comment]
Is this 1.8.6-specific?  It is running fine in my 1.8.7 setup

**Comment by timcharper** [comment]
Let me try it with 1.8.7

**Comment by timcharper** [comment]
passes on 1.8.7, and 1.9.1 for the matter. Do you think it might be indicative of a Ruby incompatibility issue?

**Comment by stffn** [comment]
Probably.  As this is non-core functionality, it is probably not worth the debugging effort.
