### ISSUE TITLE
Not compatible with ruby 1.9.2 head

### ISSUE THREAD

**Issue by IvanUkhov** [stffn/declarative_authorization#38]
Hi!

In 1.9 we can't call instance_eval passing lambdas, only procs.

<pre>
ActionView::TemplateError (wrong number of arguments (1 for 0))
</pre>

The first solution is to make the rule reader use proc instead of lambda:

<pre>
      def parse_attribute_conditions_hash! (hash)
        merge_hash = {}
        hash.each do |key, value|
          if value.is_a?(Hash)
            parse_attribute_conditions_hash!(value)
          elsif !value.is_a?(Array)
            merge_hash[key] = [:is, proc { value }]
          elsif value.is_a?(Array) and !value[0].is_a?(Symbol)
            merge_hash[key] = [:is_in, proc { value }]
          end
        end
        hash.merge!(merge_hash)
      end
</pre>

The second is calling instance_exec in the attribute validator:

<pre>
      def evaluate (value_block)
        instance_exec(&value_block)
      end
</pre>

Ivan.

**Comment by IvanUkhov** [comment]
Actually `instance_eval` is used all over the code... For example if I specify `load_method` in options for `filter_access_to` with lambda, `in_controller.rb` `load_method` fails with the same error.

**Comment by stffn** [comment]
All tests pass for me with ruby 1.9.1.  Do they work for you?  Which ruby version are you using?

**Comment by IvanUkhov** [comment]
ruby 1.9.2 (head)

**Comment by stffn** [comment]
OK, this changed on ruby in 1.9 after 1.9.1.  We are still at preview 1 for 1.9.2

Details: http://www.ruby-forum.com/topic/189422

Unfortunately, instance_exec isn't present in Ruby 1.8.6, so the only possibility is to change lambda into proc.  Let's wait for preview 2.  If you need this urgently, please fork and send me a pull request when all tests pass in 1.9.2 head.

**Comment by stffn** [comment]
Is this still an issue with preview3?

**Comment by stffn** [comment]
Ruby 1.9.2 compatibility: instance_eval problems with lambdas

Closed by 2362075d0af387ba959cf8de1d71704757b8f727.  Some details: http://www.ruby-forum.com/topic/213325
