### ISSUE TITLE
Problem with has_role?

### ISSUE THREAD

**Issue by fireharp** [stffn/declarative_authorization#39]
Hello!
I've got a problem in has_role? work. Somehow it checks only first role in array of roles given(:manager here).

```
has_role? :moderator, :admin do
     @app.approved = true
end
```

**Comment by stffn** [comment]
Actually, a specific test was missing.  But it works fine, I just added a test case.  Are you sure that the user does not have those roles?  Else, can you provide a failing test?

**Comment by fireharp** [comment]
I'm trying to fix it just now.
I'll look at your testcase first.

BTW thanks for great gem! =)

**Comment by fireharp** [comment]
OMG!

Everithing's fine. 

I'm giving up night-time coding.
