### ISSUE TITLE
Suggestion: any_roles? helper

### ISSUE THREAD

**Issue by fireharp** [stffn/declarative_authorization#40]
Hello!

I think it'll be useful to have some function like, has_role? but to be true if _any_ of given roles are in user roles.
Something like this

```
def any_role? (*roles, &block)
  user_roles = authorization_engine.roles_for(current_user)
  result = roles.any? do |role|
    user_roles.include?(role)
  end
  yield if result and block_given?
  result
end
```

**Comment by stffn** [comment]
If there is need for such a helper, we should implement it.  Personally, I haven't missed it yet.
