### ISSUE TITLE
ActiveRecord::NamedScope::Scope class has been removed in Rails3 beta3

### ISSUE THREAD

**Issue by marcocampana** [stffn/declarative_authorization#41]
declarative_authorization does not work anymore with rails3 beta3. This is due to the fact that the ActiveRecord::NamedScope::Scope class has been removed and ObligationScope inherits from it.
See:

lib/declarative_authorization/obligation_scope.rb line 45

**Comment by stffn** [comment]
Fixed in ede74884143d44a7a7b04e37cfc69d5c2c2c1f3e
