### ISSUE TITLE
Error in Authorization::AUTH_DSL_FILES

### ISSUE THREAD

**Issue by galetahub** [stffn/declarative_authorization#42]
Hi, l get error in rails 3.0.0.beta3
(gem 'declarative_authorization', :git => 'git://github.com/stffn/declarative_authorization.git')

Error reading authorization rules file with path '/config/authorization_rules.rb'!  Please ensure it exists and that it is accessible.

please fix in file "lib/declarative_authorization/authorization.rb":
AUTH_DSL_FILES = ["#{Rails.root}/config/authorization_rules.rb"] unless defined? AUTH_DSL_FILES
to 

AUTH_DSL_FILES = [Rails.root.join('config', 'authorization_rules.rb')]

**Comment by stffn** [comment]
Fixes authorization_rules.rb location for Rails 3.beta3 as gem (Closed by e584178e4422a8d22b036fb07e90c0ba771612f8)

**Comment by jpartogi** [comment]
Thanks Steffen.
