### ISSUE TITLE
TypeError (can't convert Pathname into String)

### ISSUE THREAD

**Issue by tfl** [stffn/declarative_authorization#45]
here i am - once again..

I get a TypeError after adding this little line in my posts controller: 
- filter_resource_access

The next two lines are empty - no further error messages are provided.. hmmm
- ruby 1.9.1p378
- Rails 3 - BETA3
- current git snapshot of declarative_authorization

**Comment by tfl** [comment]
it seems not to be a problem within method filter_resource_access but sometime later on. Maybe it's not even a problem in declarative_authorization.. i cant say.

**Comment by stffn** [comment]
I'm not sure. Just to be on the safe side, I added a to_s in 730afce8514b15b32fcf31319827ea573add9319 .  Please check whether this solves your issue.

**Comment by tfl** [comment]
I dont know what else do you changed but now i have this:

.../declarative_authorization/reader.rb:80:in 'rescue in parse': Illegal DSL syntax: undefined method 'privileges'for #Authorization::Reader::AuthorizationRulesReader:0xae92a38 (Authorization::Reader::DSLSyntaxError)

But: after removing .to_s from your patch i now get a speaking error saying:

.../lib/declarative_authorization/reader.rb:75:in 'instance_eval': can't convert Pathname into String (TypeError)

will look into that tomorrow ;)

**Comment by tfl** [comment]
my fault - invalid authorization declaration...
