### ISSUE TITLE
403 instead of failure message

### ISSUE THREAD

**Issue by vanboom** [stffn/declarative_authorization#46]
Hello, I am hooking declarative_authorization into my application.  If I use if_attribute in my authorization rules, the program starts throwing me back a 403 page.  

Permission denied: No matching rules found for edit for #<Client id: 3, uniqueid: "something"......

Filter chain halted as [:filter_access_filter] rendered_or_redirected.

Have you seen this before?  Where in the code should I look to understand what is going on? 
Thanks a lot!

**Comment by stffn** [comment]
This is the normal behavior if the object does not match your if_attribute rules.
