### ISSUE TITLE
should attribute_check be disabled on :new actions?

### ISSUE THREAD

**Issue by timcharper** [stffn/declarative_authorization#47]
It seems that would be a more sensible default, what do you think?

Happy to submit a patch if you agree

**Comment by timcharper** [comment]
(of course I am making reference to controllers using filter_resource_access)

**Comment by stffn** [comment]
For me, this default worked fine.  We should be careful with the changing of defaults.  If there is a broad consensus on the matter, I'd agree, though.

**Comment by timcharper** [comment]
Upon thinking about this further, I should probably update my authorization rules to not do attribute checking for new/create.  Sorry for the noise.
