### ISSUE TITLE
be noisy about mismatched method names during attribute check

### ISSUE THREAD

**Issue by timcharper** [stffn/declarative_authorization#49]
I've been bit by this a few times.  I would much prefer decl auth to be noisy about method-missing errors, rather than having the exception go straight to the log.

A patch if you agree:

http://github.com/timcharper/declarative_authorization/tree/noisy_nomethod

**Comment by stffn** [comment]
Hmm, what's wrong with raising AuthorizationUsageError?  How does it help to turn the Exception into a RuntimeError?

**Comment by timcharper** [comment]
AuthorizationUsageError is fine, my motivation for this patch was to make the error not be engulfed and for decl auth to fail silently (well, I know its going to the log... but still, I wouldn't expect errors like these to go to the log.

(If there is a typo, it seems the error should be raised. I like the way you gave it a more descriptive error, so would be a proponent of that.

**Comment by timcharper** [comment]
I will update the patch to continue to use AuthorizationUsageError

**Comment by timcharper** [comment]
I have updated the patch to make the in_controller.rb rescue rescue at NotAuthorized instead of AuthorizationError (AttributeAuthorizationError and NotAuthorized will be caught and logged, AuthorizationError will cause a terminal error).

http://github.com/timcharper/declarative_authorization/tree/noisy_nomethod

**Comment by stffn** [comment]
You are right, those errors shouldn't be caught by default.  Committed as bbb8acb0b679295e2cd4d88ce9595ceaf58c7da6
