### ISSUE TITLE
Do not raise AuthorizationUsageError when object does not have required attribute

### ISSUE THREAD

**Issue by IvanUkhov** [stffn/declarative_authorization#5]
object_attribute_value raises AuthorizationUsageError exception when the send method fails with NoMethodError. It would be better if in this case the method returned just nil flunking the rule. In my application I have polymorphic association: Paragraph belongs_to(:owner, :polymorphic => true), [ ManPage, WomanPage ] has_many(:paragraphs, :as => :owner). Owners have different attributes. Rules look like this:

has_permissions_on :paragraphs, :to => :manage do

  if_attribute :owner => { :man => is { user } }

  if_attribute :owner => { :woman => is { user } }

end

So WomanPage does not have :man, and we get NoMethodError.

**Comment by stffn** [comment]
The most common case still is a typo.  That is why there currently is this fail-fast approach to raise.  That's why I'd consider a flag on has_permission_on to allow missing attributes.

For your specific case: is there a reason not to just have man/woman methods returning nil on the other class?

**Comment by IvanUkhov** [comment]
yes, there is a reason, it's just a simplified example, in my app those classes have a lot of different attrifutes, and there are many classes and many polymorphic association, and defining a lot of fake attributes is not the way to go for me, please add this [allow missing attributes] option, it'll be very useful! thanks! now i just patch the plugin myself returning nil from object_attribute_value...

**Comment by IvanUkhov** [comment]
By the way, what is the common case? What idea is behind this exception raising?

**Comment by IvanUkhov** [comment]
There is another solution. According to the documentation conditions in if_attributes are ORed, but they can't be ordered, so when the first one is false, the rest are still been checked. But if we could order them, it wouldn't happen. Some thing like this:

if_attribute [ { :owner_type => 'Man' }, { :owner => { :man => is { user } } } ]

if_attribute [ { :owner_type => 'Woman' }, { :owner => { :woman => is { user } } } ]

What do you think?

**Comment by stffn** [comment]
The common case is that all attributes are known beforehand.  Any non-existant attribute thus is a typo which should lead to a failure as soon as possible (fail-fast).

**Comment by IvanUkhov** [comment]
So how about ordering? Please implement this feature and additional option to has_permissions_on =) Thanks!

**Comment by stffn** [comment]
This really is an edge case.  I think the best approach would be an application-wide switch, e.g. setting Authorization.raise_on_missing_attribute = false.  If you provide such a patch, I'm happy to include it.

**Comment by IvanUkhov** [comment]
Mmm.... and what about

has_permissions_on :paragraphs, :to => :manage, :join_by => :and do

  if_attribute :owner_type => 'Man'

  if_attribute :owner => { :man => is { user } }

end

has_permission_on :paragraphs, :to => :manage, :join_by => :and do

  if_attribute :owner_type => 'Woman'

  if_attribute :owner => { :woman => is { user } }

end

?

**Comment by stffn** [comment]
That might work.  The if_attribute statements are held in an array and checked in order.  Please test it.

**Comment by IvanUkhov** [comment]
yes, that works =)
