### ISSUE TITLE
premature loading of railsengine.rb

### ISSUE THREAD

**Issue by timcharper** [stffn/declarative_authorization#51]
loading railsengine.rb where it was was premature: other deps need to be loaded first

See the patch for more details:

http://github.com/timcharper/declarative_authorization/tree/rails_engine_loading_patch

**Comment by stffn** [comment]
Sounds plausible.  How do I reproduce the error?

**Comment by timcharper** [comment]
Hmm... actually I just went through these steps and it worked.

Since I'm not using ActiveRecord (using MongoMapper), I've got this code to load declarative_authorization:

```
require "declarative_authorization/rails_legacy"
require "declarative_authorization/helper"
require "declarative_authorization/in_controller"

ActionController::Base.send :include, Authorization::AuthorizationInController
ActionController::Base.helper Authorization::AuthorizationHelper
```

Therefore, the dependencies get loaded in this fashion, and the error occurs:

```
lib/declarative_authorization/obligation_scope.rb:45: uninitialized constant Authorization::ActiveRecord (NameError)
    lib/declarative_authorization/in_model.rb:3
    lib/declarative_authorization.rb:4
    lib/declarative_authorization/railsengine.rb:1
    lib/declarative_authorization/authorization.rb:2
    lib/declarative_authorization/helper.rb:2
```

So, the problem is _really_ railsengine.rb requiring lib/declarative_authorization.rb, which forces me to use the whole plugin. Before, when using rails 2.3.5, railsengine.rb was never loaded, so I didn't run into this problem.

I still believe that:
- railsengine.rb should be loaded by lib/declarative_authorization.rb and not lib/declarative_authorization/authorization.rb, so it can be optionally loaded.
- railsengine.rb should not load lib/declarative_authorization.rb, giving the plugin consumer the choice of which pieces to load (in the case that not all pieces are compatible with the environment of choice, as was my case)

**Comment by timcharper** [comment]
Yikes... this is bad

Authorization::Engine is defined here

http://github.com/stffn/declarative_authorization/blob/b18d29dedb2cba0fe15dfb24893efb5bd03f8cfa/lib/declarative_authorization/authorization.rb#L60

And here:

http://github.com/stffn/declarative_authorization/blob/b18d29dedb2cba0fe15dfb24893efb5bd03f8cfa/lib/declarative_authorization/railsengine.rb#L5

So, class Authorization::Engine < Rails::Engine MUST be loaded before class Authorization::Engine.  Ruby doesn't complain because the second doesn't define an ancestor, so it happily uses the previously defined Rails::Engine ancestor. However, these two classes are clearly not related.

**Comment by timcharper** [comment]
and... I still can't get /authorization_rules to load, even when fixing these issues.  I have branched from your master and updated the patch here:

http://github.com/timcharper/declarative_authorization/tree/rails_engine_loading_patch

**Comment by timcharper** [comment]
I have updated the patch commit message and patch to match my findings. Please see:

http://github.com/timcharper/declarative_authorization/tree/rails_engine_loading_patch

**Comment by stffn** [comment]
Thanks.  Worked fine here and is committed as 3d7dce334a1b601e0ac6d4f7956e424760b7292d
