### ISSUE TITLE
Check user attribute

### ISSUE THREAD

**Issue by woto** [stffn/declarative_authorization#52]
Hi. Sorry for bad English. I'm just learning Ruby On Rails therefore my question may be odd.
Is there way to write a rule with a condition on user fields? For example i need to allow to view page only if user email is not empty otherwise redirect him on profile page. I saw if_attribute, but seem's it's only for testing associated object.

Thanks in advance

**Comment by stffn** [comment]
Please use the mailing list for usage questions.

At first sight, I'd say this isn't an authorization issue but rather belongs into the business logic in your controller.
