### ISSUE TITLE
html_safe/safe_concat issues with recent commit 3345e04b90e4848d8f67

### ISSUE THREAD

**Issue by e9digital** [stffn/declarative_authorization#54]
I have been bundling declarative_authorization straight from the repo in a rails 3 project I'm building and ran into some perplexing behavior today after running bundler install.

The layout rendered properly, but everything inside was rendering fully HTML escaped.  All yields, tags, rendered partials, etc.  On a few pages that require auth I was getting an error "undefined method safe_concat" for String.  

It turns out that today's commit to declarative_authorization was causing the issue.  I rolled back to yesterday's and the problem disappeared.

I know that's not much of a bug report, and it very well may be that something I've done (incorrectly) somehow conflicted with declarative_authorization.  But I thought you should be aware that today's commit caused an issue with at least one Rails 3 project.

**Comment by stffn** [comment]
You are right.  There was an error in that commit and the tests didn't show it. Fixed in d241f518485a18a8b37c3b8469c60e4f0eda086f

**Comment by e9digital** [comment]
I'm still getting the same behavior in d241f51.  Sorry I can't be more detailed.  I'll have time to look into this tonight hopefully if it's still an issue.

All I know currently is that I'm getting a page full of ampersands and semicolons on all public pages, everything right down to the rails built in helper tags are HTML escaped.  And using Devise, I get this error on pages that redirect to login: "ActionView::Template::Error (undefined method `safe_concat' for #String:0x7f6d78bb0778)".  Presumably this is because of a conflict between whatever has changed in declarative_auth and the way Devise handles html_safe?  Pure guesswork.

I get the same behavior with both the rails beta 3 gem and edge.  Rolling back to declarative_auth ad95b833b stops the issue.

**Comment by e9digital** [comment]
I looked into it.  (Probably should have sooner but I didn't realize the commit was only a few lines).  The fix updated the legacy fix to look in the right place for the html_safe method, but introduced a different bug.  #instance_methods returns an array of strings and the fix is looking for a symbol.  Result is that html_safe gets overwritten in rails 3.

**Comment by stffn** [comment]
Unfortunately, I don't have any test case for this issue available.  Have you checked whether your proposed change fixes the issue?

**Comment by e9digital** [comment]
It does fix it, yes.  The issue is that #instance_methods returns methods as an array of strings.  The current commit is looking for the symbol :html_safe in that array but it should look for the method as a string.  As a result, the method isn't found and String#html_safe is overwritten in all cases.

**Comment by stffn** [comment]
Then, it should be really be fixed in 5fc78f8acff15156572002d22f04d13775c3c020

**Comment by e9digital** [comment]
Great.  Looks good.  Thanks for your quick response!

**Comment by stffn** [comment]
So, another try. 35ec81b5404c3ee495dfec3aa83e03c7429149cf should solve it for good.  Please report any remaining problems.
