### ISSUE TITLE
Forgiving notation for to  in DSL block

### ISSUE THREAD

**Issue by bterkuile** [stffn/declarative_authorization#57]
Now in a has_permission_on block you can use to in two different manners:
to :manage
or
to :update, :destroy
But since the notation without a block is done using an array I am tempted to use an array in the block as well:
to [:update, :destroy]

To handle this (no error is generated, but no security applied) I think adding a flatten to privs in reader.rb should solve the problem.
      def to (*privs)  
        raise DSLError, "to only allowed in has_permission_on blocks" if @current_rule.nil?  
        @current_rule.append_privileges(privs.flatten)  
      end

**Comment by stffn** [comment]
Yes, that's a nice improvement.  I just committed a patch for that
