### ISSUE TITLE
Support additional operators in authorization DSL

### ISSUE THREAD

**Issue by aepstein** [stffn/declarative_authorization#59]
This patch was cited in another issue.  Any reason it can't be incorporated into the main branch?

http://github.com/trooster/declarative_authorization/commit/65659c6a576565664ba6a69660f1a31331a9ce5d

Having gt, lt, etc. operators would enable a lot more functionality (e.g. allow someone to change records based on timestamp).

**Comment by stffn** [comment]
As remarked in the other issue, this patches misses tests for the operators.

**Comment by aepstein** [comment]
Oops... missed that.  I've forked from your source today and added tests that I _think_ are sufficient.  Let me know what you think.

http://github.com/aepstein/declarative_authorization/commit/2127a77f0facdf23f966b6661265d3a36478b9a5

An extra note on this -- my text editor stripped trailing whitespace from each line and I made a subsequent commit that adds a line break for readability.

**Comment by stffn** [comment]
Thanks, the tests look good.  Is it possible for you to separate the whitespace changes into a separate commit?  That would really ease the effort of understanding the actual changes.

**Comment by aepstein** [comment]
Ok, here's a commit that has trailing whitespaces removed:

http://github.com/aepstein/declarative_authorization/commit/0686a91949f5c65da868e65c52ef3637c9f285fa

You can DIY with git-diff  --ignore-space-change and git-apply.

**Comment by stffn** [comment]
Committed as 17caf95eb61b0c45da9abf0b00fe47aec5b28c0b
