### ISSUE TITLE
in_controller.rb requires that the params[:id] be "id"... I'm using params[:post]

### ISSUE THREAD

**Issue by lancejpollard** [stffn/declarative_authorization#60]
I am getting this error when accessing any route:

```
undefined method `to_i' for {the find hash}:Hash
....
app/models/post.rb:50:in `find'
....
```

In my routes I have this:

```
match '*request_path/post/:post' => "posts#index"
match '*request_path' => "posts#show", :as => :post
```

So I get in the params `params[:request_path]` and `params[:post]`.  The following method (line 139 in `in_controller.rb`) requires `params[:id]`.

```
def load_controller_object (context_without_namespace = nil) # :nodoc:
  instance_var = :"@#{context_without_namespace.to_s.singularize}"
  model = context_without_namespace.to_s.classify.constantize
  instance_variable_set(instance_var, model.find(params[:id]))
end
```

Is there a more dynamic way to do that?  I think `inherited_resources` does it a bit more dynamically with `def object_param...`.

**Comment by stffn** [comment]
The API docs for filter_resource_access list the possibilities of how to override the load method for the current object. Does this help in your case?
