### ISSUE TITLE
Support for mongodb/mongoid

### ISSUE THREAD

**Issue by ckgagan** [stffn/declarative_authorization#61]
hi
i tried using mongodb with declarative authorization but could not succeed.
Actually i got the following error when using it with mongodb 
gems/declarative_authorization-0.4.1/lib/declarative_authorization/obligation_scope.rb:45:in `module:Authorization': uninitialized constant Authorization::ActiveRecord (NameError)
Mongodb dosent use ActiveRecord for sure but the declarative authorization is trying to use ActiveRecord and is causing error.
Did i miss any thing due to which this error is coming or did i miss any thing to let mongodb and declarative authorization to work together.
Please help....

**Comment by stffn** [comment]
There is no explicit mongodb support in decl_auth.  On the other hand, I am happy to except patches in that direction.  I know that there were discussions on using decl_auth without ActiveRecord so you might have a better chance if you ask at the mailing list.

**Comment by ckgagan** [comment]
thanks stffn for the quick reply
Some one had already forked this project and made some changes in the code. This worked for me. But authorization_rule visualization cannot be view.
Here is the link:
http://github.com/opusmagnum/declarative_authorization/commit/79ccff34233b2371299c3ff66a18ad37be08d9c6

**Comment by sandstrom** [comment]
Got the same issue; would love to use declarative_authorization with Mongoid and MongoDB. +1

**Comment by vintikzzz** [comment]
https://github.com/vintikzzz/declarative_authorization/commit/9980e42aba02c2a2386c06620c96e592d929da56 - the same commit but was made quite earleier ))) Works fine!

**Comment by elubow** [comment]
I think it's worth pointing out that this commit, although allow decl_auth to work fine with MongoID, negates the use of the model related aspects.  For me this wasn't a deal breaker, but it might be for others.  I think the key here is that at some point (and I might do it if I find the need for the model related hooks in my application) that the dependency on AR needs to be removed.

**Comment by tilo** [comment]
why not make declarative_authorization completely independent of the persistence layer?

**Comment by stffn** [comment]
Please, go ahead.  Much of the query rewriting stuff is SQL-specific, though.  Not sure how this could be implemented for NoSQL.  Any suggestions?
