### ISSUE TITLE
Rails generator errors after installation of Declarative_Authorization

### ISSUE THREAD

**Issue by AMC** [stffn/declarative_authorization#63]
Rails 3.0.0.beta4
Ruby 1.9.2dev
Bundler 0.9.26
Declarative_Authorization 0.4.1

After installation of Declarative_Authorization using Bundler I receive errors when using Rails generators such as scaffolding.

If Declarative_Authorization is uninstalled Rails generators function normally.

Error Message:
C:\rails\devise>rails generate scaffold user name:string
C:/Users/Andrew/.bundle/ruby/1.9.1/gems/declarative_authorization-0.4.1/lib/declarative_authorization/obligation_scope.rb:44:in `<module:Authorization>': uninit
ialized constant ActiveRecord::NamedScope::Scope (NameError)
        from C:/Users/Andrew/.bundle/ruby/1.9.1/gems/declarative_authorization-0.4.1/lib/declarative_authorization/obligation_scope.rb:1:in`<top (required)>'
        from C:/Users/Andrew/.bundle/ruby/1.9.1/gems/declarative_authorization-0.4.1/lib/declarative_authorization/in_model.rb:3:in `require'
        from C:/Users/Andrew/.bundle/ruby/1.9.1/gems/declarative_authorization-0.4.1/lib/declarative_authorization/in_model.rb:3:in`<top (required)>'
        from C:/Users/Andrew/.bundle/ruby/1.9.1/gems/declarative_authorization-0.4.1/lib/declarative_authorization.rb:4:in `require'
        from C:/Users/Andrew/.bundle/ruby/1.9.1/gems/declarative_authorization-0.4.1/lib/declarative_authorization.rb:4:in`<top (required)>'
        from C:/bin/pik/Ruby-192dev-preview3-1/lib/ruby/gems/1.9.1/gems/bundler-0.9.26/lib/bundler/runtime.rb:46:in `require'
        from C:/bin/pik/Ruby-192dev-preview3-1/lib/ruby/gems/1.9.1/gems/bundler-0.9.26/lib/bundler/runtime.rb:46:in`block (2 levels) in require'
        from C:/bin/pik/Ruby-192dev-preview3-1/lib/ruby/gems/1.9.1/gems/bundler-0.9.26/lib/bundler/runtime.rb:41:in `each'
        from C:/bin/pik/Ruby-192dev-preview3-1/lib/ruby/gems/1.9.1/gems/bundler-0.9.26/lib/bundler/runtime.rb:41:in`block in require'
        from C:/bin/pik/Ruby-192dev-preview3-1/lib/ruby/gems/1.9.1/gems/bundler-0.9.26/lib/bundler/runtime.rb:40:in `each'
        from C:/bin/pik/Ruby-192dev-preview3-1/lib/ruby/gems/1.9.1/gems/bundler-0.9.26/lib/bundler/runtime.rb:40:in`require'
        from C:/bin/pik/Ruby-192dev-preview3-1/lib/ruby/gems/1.9.1/gems/bundler-0.9.26/lib/bundler.rb:89:in `gem_require'
        from C:/rails/devise/config/application.rb:7:in`<top (required)>'
        from C:/bin/pik/Ruby-192dev-preview3-1/lib/ruby/gems/1.9.1/gems/railties-3.0.0.beta4/lib/rails/commands.rb:15:in `require'
        from C:/bin/pik/Ruby-192dev-preview3-1/lib/ruby/gems/1.9.1/gems/railties-3.0.0.beta4/lib/rails/commands.rb:15:in`<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in`<main>'

**Comment by AMC** [comment]
Per: http://www.railsplugins.org/plugins/281-declarative-authorization
Modified Gemfile with the following:
gem 'declarative_authorization', :git => "http://github.com/stffn/declarative_authorization.git"

**Comment by AMC** [comment]
Apparently that fixed it. The file at rubygems.org must not be up to date yet.

**Comment by stffn** [comment]
It's about time for the next release.  I just held off to have complete Rails 3 support in decl_auth 0.5.  If there are no issues with beta4 and Ruby 1.9.2rc2, I'd go ahead and release 0.5.
