### ISSUE TITLE
undefined method `info' for nil:NilClass

### ISSUE THREAD

**Issue by shamne** [stffn/declarative_authorization#64]
undefined method `info' for nil:NilClass
when adding filter_access_to :all to the controller
it's probably logger.info, i don't know why but logger is undefined

**Comment by shamne** [comment]
it's probably the same as issue # 6, there was a problem with logger.debug

**Comment by stffn** [comment]
Hmm, I don't think that it is the same issue.  Then, the code was executed in a different object context.  Please post a backtrace?

**Comment by shamne** [comment]
sorry Steffen that was another problem, not with your plugin, i saw that issue # 6 and thought it's the same
