### ISSUE TITLE
Conflict? with rails3-jquery-autocomplete gem.

### ISSUE THREAD

**Issue by kinopyo** [stffn/declarative_authorization#65]
I was trying to use declarative_authorization with rails3-jquery-autocomplete(http://github.com/crowdint/rails3-jquery-autocomplete.git).

My app is a pretty simple application which has these models: Article, Tag, User. 
In my articles_controller, I write down the code:

```
# for jquery plugin autocomplete
autocomplete :tag, :name
# for Delcarative Authorization
filter_resource_access
```

And when I input a character in the input tag, it was supposed to active the autocomplete to search the tag table, but it failed. If I comment out the filter_resource_access line, it works! I used admin user to login so I'm sure I have the authority to select from the tag table.

I also check the log file, when comment out filter_resource_access, the log looks like this:

```
Parameters: {"term" => "a" }
SELECT "users".* FROM "users" WHERE ("users"."id" = 3) LIMIT 1
SELECT "tags".* FROM "tags" WHERE(LOWER(name) LIKE 'c%') ORDER BY name ASC LIMIT 10
```

But when filter_resource_access is active, the log looks like this:

```
Parameters: {"term" => "a" }
SELECT "users".* FROM "users" WHERE ("users"."id" = 3) LIMIT 1
ActiveRecord::RecordNotFound (Couldn't find Article without an ID)
```

I don't understand why the ActiveRecord::RecordNotFound raised? What make it look for an article record rather than tags? Any thoughts would be helpful.

**Comment by stffn** [comment]
I don't think there is a conflict between the plugins.  While you didn't give the context, I suppose that you are talking about the ArticlesController.

As decl_auth cannot infer from the action name whether it is a member or collection action, decl_auth will assume that the autocomplete action is a member action by default.  Thus, it will try to load an @article object from params[:id] as it does for show.  You have to declare the action to be a collection to circumvent this behavior.  Please have a look at the API doc on that.

As this is not a feature request or bug report, I'd prefer to discuss it on the mailing list for a larger audience.

**Comment by kinopyo** [comment]
Thanks for your comment! I check out the API doc and solve the problem.

You're right, there is not a conflict between them, I followed your advise like this.

```
#in ArticlesController
filter_resource_access :additional_collection => :autocomplete_tag_name

#in authorization_rules.rb, add the :autocomplete_tag_name action to the role
has_permission_on :articles, to => [:new, :create, :autocomplete_tag_name]
```

It works! Thanks a lot!
