### ISSUE TITLE
Error in Rails 2.2.2

### ISSUE THREAD

**Issue by stffn** [stffn/declarative_authorization#67]
Exiting c:/ruby/lib/ruby/gems/1.8/gems/declarative_authorization-0.5/lib/
declarative_authorization/authorization.rb:23: undefined method `join' for "C:/
aGreenDoor/Trunk/Trunk":String (NoMethodError)
from c:/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'

**Comment by insic** [comment]
i am having the same error. I am new to RoR so I do not know whats the cause :)

**Comment by stffn** [comment]
Rails.root was no Pathname object prior to 2.3 (closed by 1b710bfb9735597865ae88b9119d9158a2736c43)
