### ISSUE TITLE
deprecation warnings with >= 3.0.0.rc (router dsl)

### ISSUE THREAD

**Issue by bhh** [stffn/declarative_authorization#69]
rails2 routes will be no longer supported in the future >= 3.1

**Comment by dgm** [comment]
DEPRECATION WARNING: You are using the old router DSL which will be removed in Rails 3.1. Please check how to update your routes file at: http://www.engineyard.com/blog/2010/the-lowdown-on-routes-in-rails-3/. (called from <top (required)> at [path]/vendor/plugins/declarative_authorization/config/routes.rb:4)

**Comment by dgm** [comment]
Here's gist with it rewritten to get rid of the warning:  http://gist.github.com/567160

**Comment by stffn** [comment]
Thanks, I submitted it to the master branch
