### ISSUE TITLE
completely replace before_filter cruft on User

### ISSUE THREAD

**Issue by iva2k** [stffn/declarative_authorization#77]
I completely adore declarative_authorization. It gives control over permissions in one concise place.

I like the "includes" approach, which is very handy for setting up user self-registration and login logic, then propagating it to other roles via "includes :guest".

However, I cannot figure out how to set up rules with includes such that: 
- guest can self-register  
- for logged-in users only admin role can create new users 

The first part actually works (guests can self-register). That's what I have:
    authorization do
      role :guest do
        has_permission_on :users, :to => [:create]
        has_permission_on :roles_users, :to => [:create]
        has_permission_on :user_sessions, :to => [:create]
        has_permission_on :user_sessions, :to => [:delete] do
          if_attribute :record => is {user}
        end
        ## IMPORTANT! This rule is required for AuthLogic login to work.
        ## It shall be propagated to all roles (either via include, or direct copy)
        has_permission_on :users, :to => :update do
          if_attribute :id => is {user.id}
        end
      end

```
  role :User do
    includes :guest
    ...
  end

  role :Administrator do
    includes :guest
    has_permission_on [:users, :roles_users, :categories, :products], :to => :manage
    ...
  end
end
```

With includes, once the permission is given, I cannot revoke it. So all logged in users can get to /users/new URL and have a form. I want to remove it with DA. I understand that DA cannot revoke given permission, so I am trying conditional block in role :guest like
      role :guest do
        has_permission_on :users, :to => [:create] do
          if_attribute ???
        end
And here I cannot find anything in the documentation or examples or the DA source code... I want a conditional statement that checks if user is currently logged in or not.

Any recommendations?
(Please don't point out the obvious - dropping the "includes" altogether - I know that would work, but it will be against DRY.)

**Comment by iva2k** [comment]
What will be very useful to solve this problem (and few others that I have around UserSession and authlogic) is a simple macro that checks login state (or calls a method that does the check), such as:
      role :guest do
        has_permission_on :users, :to => [:create] do
          unless_condition :current_user
        end
Two macros would be handy: if_condition and unless_condition, obviously.

**Comment by stffn** [comment]
I think this kind of discussion is better catered for on the mailing list.  Please take it there for further discussion.

I would approach your problem by introducing another role, :basic_role and have :guest and all other roles include it.  Then, you could add your users#create permission in the :guest role.
