### ISSUE TITLE
error with authorization rules built in controller/view, Ubuntu

### ISSUE THREAD

**Issue by vanboom** [stffn/declarative_authorization#78]
ActionView::TemplateError (undefined local variable or method `authorization_rules_path' for #ActionView::Base:0xb5db2530) on line #3 of /usr/lib/ruby/gems/1.8/gems/declarative_authorization-0.5.1/app/views/authorization_rules/index.html.erb:

I am getting this error - missing "authorization_rules_path" after porting my application from a Windows box where things work perfectly to a Linux Ubunto 10.4. 

I am using 0.5.1 confirmed on both machines.

Any advice on how I could trace this down - thanks in advance :)
Don

**Comment by stffn** [comment]
Are you sure that the plugin's routes are set up correctly?

**Comment by vanboom** [comment]
I am using the same routes.rb file on both machines, however there are no explicit routes entries for the plugin.

**Comment by vanboom** [comment]
OH - the difference is development vs. production mode.  It does not appear in production mode by default.  Sorry for the false alarm.
