### ISSUE TITLE
"can't modify frozen array" error while including roles

### ISSUE THREAD

**Issue by Thorfinson** [stffn/declarative_authorization#79]
while trying to define my authorizations with includes e.g.: 'includes :user', i stumbled over the error "can't modify frozen array" in line 301 of 'declarative_authorization/authorization.rb'. The Error seems to be fixed with replacing line 299 from  'flattened_roles = roles.clone.to_a' to  'flattened_roles = roles.dup.to_a'.

**Comment by stffn** [comment]
Is User#role_symbols returning a frozen array in your case?  It sounds sensible to use dup instead of clone but I'd like to have a failing test first.

**Comment by stffn** [comment]
Fixed exception from frozen role_symbols

Closed by 150e4f10b36946f7d2bdbbc609c7b0ef2e20d112
