### ISSUE TITLE
if_attribute produces wrong SQL

### ISSUE THREAD

**Issue by tztz** [stffn/declarative_authorization#80]
Hello everybody,

somehow a rule produces wrong SQL. I want to share this with you.

I have the following rule

```
MAINTAINABLE_OBJECTS = [:games, :game_templates, :artifacts, :artifact_groups, :artifact_overlays, :global_assets, :motypes, :states]

role :partner do
  includes :user
  #FIXME: does not work
  has_permission_on MAINTAINABLE_OBJECTS, :to => [:read, :read_attachment] do
    if_attribute :accessible => true
  end
end

privilege :read, :includes => [:index, :show]
```

accessible is a method in MaintainableObject (the super class of Game, Artifact, etc.) which in turn returns self.public. public is an attribute of MaintainableObject. BTW: I cannot use public directly since this does not work either; but this is another issue.

If I now try to access the index page of a maintainable object, let's say game, the following SQL is generated:

```
PGError: ERROR:  invalid input syntax for integer: "t"
LINE 1: ...."user_id" = 5) OR ("maintainable_objects"."id" = 't')) AND ...

: SELECT * FROM "maintainable_objects" WHERE (("maintainable_objects"."id" = 5) OR   ("maintainable_objects"."user_id" = 5) OR ("maintainable_objects"."id" = 't')) AND ( ("maintainable_objects"."type" = 'Game' ) )  ORDER BY lower(maintainable_objects.name) LIMIT 25 OFFSET 0
```

As you can see 'id' is compared against the boolean value 'true' (maintainable_objects"."id" = 't'). This obviously does not make sense.

Any ideas on this one?

Regards,
Mark

**Comment by stffn** [comment]
You cannot use non-attribute methods in the conditions.  It would be one order of magnitude more complex to build queries from arbitrary methods (if it was possible at all, which is not the case of course).

**Comment by tztz** [comment]
Huh?! That actually irritates me a lot since I use non-attribute methods and they _do_ work! For example the following code

```
has_permission_on MAINTAINABLE_OBJECTS-[:games], :to => [:manage] do
  if_attribute :employing_games => contains {user.active_game} # employing_games are the games which employ/utilize the resp. maintainable object
end
```

uses the method employing_games which is defined in every maintainable object. For Artifact it looks like this:

```
def employing_games
    self.game_templates.map do |gt|
        gt.games
    end.flatten.uniq
end
```

And for the record: there is no has_many association or attribute called 'employing_games'.

Maybe I understood you wrong.
