### ISSUE TITLE
Attributes check for collections (ie. A presenter can't subscribe to its own workshops)

### ISSUE THREAD

**Issue by Sephi-Chan** [stffn/declarative_authorization#84]
Hi,

I my project, there are workshops and presenters. A presenter can't subscribe to its own workshops.

I have an index page in which I list coming workshops. For each workshop I have a link to quickly subscribe/unsubscribe :

```
- if permitted_to? :subscribe, workshop
  %p.actions
    - if current_user.workshops.include?(workshop)
      = link_to "Unsubscribe", unsubscribe_workshop_path(workshop)
    - else
      = link_to "Subscribe", subscribe_workshop_path(workshop)
```

But… Even when the workshop presenter is the current user, the link appear… Here are my rules for presenter (one of the role my current user has):

```
role :presenter do
  has_permission_on :workshops, :to => [ :index, :new, :create, :show, :edit, :update, :delete ]
  has_permission_on :workshop,  :to => [ :subscribe, :unsubscribe ] do
    if_attribute :presenter => is_not { user }
  end
  includes :user
end
```

How can I achieve what I want ? How to force the attribute check (because there is none in the controller since the query find a collection of workshop, not only one) ?

Thanks a lot

**Comment by stffn** [comment]
This seems like a usage-related request.  Please turn to the Mailing list instead for usage questions.
