### ISSUE TITLE
Add flag to disable model level checks for a single object

### ISSUE THREAD

**Issue by tobsch** [stffn/declarative_authorization#88]
Hi there,

IMHO it would be nice if there was a flag to disable access checks for a particular Model instance (eg: for example a user thats being created in a cronjob).

user = User.new(:foo => 'bar')
user.using_access_control(false)
user.save!

Is there anything that speaks against this?
Otherwise we would implement it and send a pull request.

Best,

Tobias

**Comment by stffn** [comment]
Why not disable access control for the one action in the thread?  You don't influence any other actions since disabling it is thread-specific.
