### ISSUE TITLE
Why cant use Hash as an attribute value for Array attributes?

### ISSUE THREAD

**Issue by IvanUkhov** [stffn/declarative_authorization#9]
authorization.rb, line 412:

```
    if value.is_a?(Hash)
      if attr_value.is_a?(Array)
        raise AuthorizationUsageError, "Unable evaluate multiple attributes " +
          "on a collection.  Cannot use '=>' operator on #{attr.inspect} " +
          "(#{attr_value.inspect}) for attributes #{value.inspect}."
```

What if i want to check length of some association?

has_permission_on :pages, :to => :publish do

  if_attribute :paragraphs => { :length => is_not { 0 } }

end

**Comment by stffn** [comment]
You won't be able to use with_permissions_to for that model then.  If we'd allow it, the error in with_permissions_to would be hard to debug.  What about :paragraphs => is_not {[]}?

**Comment by IvanUkhov** [comment]
0 was just for example...
ok, so i have to make a helper method in the model... (

**Comment by stffn** [comment]
A "won't fix"
