### ISSUE TITLE
has omnipotence and obligation scope

### ISSUE THREAD

**Issue by dgm** [stffn/declarative_authorization#90]
I have a weird issue.  I just discovered has_omnipotence, and turned that on for y admin role, but the admin suddenly lost the ability to list all users.

<pre>
    role :admin do
        has_omnipotence
    end

    role :authenticated_user do
         has_permission_on [:users], :to =>  [:index,:show, :edit, :update] do
            if_attribute :id => is { user.id }
         end
        ...
     end
</pre>

Like this, User.has_permissions_to(:index) with an admin role only lists the current user.  If I change it to User.has_permissions_to(:read), it works.

I traced through the code a bit and see that the omnipotence correctly passes permit! but I suspect the problem is in the call to obligation_scope_for - it returns a scope that matches that authenticated_user role, when it should not return any scope at all.

**Comment by stffn** [comment]
So the admin also has the :authenticated_user role?

**Comment by dariocravero** [comment]
Hi @stffn,

I'm having thre same issue that @dgm is experiencing. Our roles are different but in our case, the admin is algo an authenticated_user.

Why is it that omnipotence doesn't take over the regular role?
Thanks :)

**Comment by dgm** [comment]
I'll try that out...  the point is that has_omnipotence should include, no, supercede, every role possible, explicit or not.  :)
