### ISSUE TITLE
Intermittent permission

### ISSUE THREAD

**Issue by jsmpereira** [stffn/declarative_authorization#92]
I'm having an issue with my BookmarksController.

I'm using:

```
filter_access_to :all, :attribute_check => true
```

It seems that in some requests the below rule works correctly and on others it denies access.

```
has_permission_on :bookmarks, :to => [:manage, :shared] do
  if_attribute :company => {:employees => contains {user}}
end
```

I'd wager it has something to do with class loading. Production env seems to not be affected.
If I restart the server, the first request for index allows access; if I hit refresh I get access denied <code>Permission denied: index not allowed for...</code>

On <code>authorization.rb</code> I added a <code>logger.debug</code> line where I inspect <code>attr_value</code> and <code>evaluated</code> on <code>:contains</code> condition in <code>validate?</code> and behavior seems to be correct. I remove it and the intermittent behavior returns.

The controller in question has the same config and rules others have that do not show this behavior.

Any ideas on how to really get to the bottom of this.

Thanks

**Comment by stffn** [comment]
I'm not sure that this is a decl_auth bug.  And it seems to be difficult to reproduce if it was.  Maybe try it on the mailing list for a broader audience?

**Comment by jsmpereira** [comment]
Will do. Thanks
