### ISSUE TITLE
Controller test in apps with devise

### ISSUE THREAD

**Issue by kubi-dev** [stffn/declarative_authorization#95]
We use both devise and devlarive_authorization in our app. And we have huge problem with controller tests.
Both of gems offers special test helpers:
- sign_in for devise
- get_with, post_with etc. for declarative_authorization

The problem is they don't work correct together. If we sign is user via devise sign_in helper and after that we make request via declarative_authorization helpers than user is not logged in.

**Comment by stffn** [comment]
*_with are designed to set a specific user.  To do that, the helpers needs to assume some aspects of how the application handles authentication.  This will naturally interfere with some authentication schemes.  Please feel free to suggest patches to make them work well with each other or use the mailing list to discuss the usage.

**Comment by csommerauer** [comment]
It seems to work for Rails 3.0.6, devise 1.1.5, declarative authorization 0.5.3. The sign_in test helper from devise adds the key/value pair "warden.user.user.key" => ["User",id] to the session and one has to explicitly add the session to the declarative_authorization get_with helper. The [*_with methods](https://github.com/stffn/declarative_authorization/blob/master/lib/declarative_authorization/maintenance.rb#L198)  call the [request_with method](https://github.com/stffn/declarative_authorization/blob/master/lib/declarative_authorization/maintenance.rb#L183) which defaults the session argument to an empty hash unless one explicitly provides the session.

And without the above mentioned key/value pair in the session when calling get_with, one will not get past devise's authenticate_user! before filter

The following test in the users_controller_test.rb works when trying to access the users_controller show action which is  included in the filter_resource_access and has an appropriate rule listed in the authorization rules:

``` ruby
#config/authorization_rules.rb
role :authenticated do
    has_permission_on :users, :to => [:show] do
      if_attribute :id => is { user.id}
    end
end

#app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  filter_resource_access 

  def show    #@user is already loaded through filter_resource_access method of the declarative_authorization gem
    respond_to do |format|
      format.html  { render :action => :show}
    end
  end
end

# test/test_helper.rb
ENV["RAILS_ENV"] = "test"
require File.expand_path('../../config/environment', __FILE__)
require 'declarative_authorization/maintenance'
require 'rails/test_help'

class ActiveSupport::TestCase
  include Authorization::TestHelper
  fixtures :all
end

# test/functional/user_controller_test.rb
require 'test_helper'

class UsersControllerTest < ActionController::TestCase
  include Devise::TestHelpers
  setup do
    @user = users(:authenticated)  #this user must obviously have symbol :authenticated as an element of the role_symbols array
   end

  test "should get to show action if current user is equal to the called resource" do
    sign_in @user
    get_with @user, :show,{:id=> @user.id}, session #this is where the session from sign_in is added to get_with
    assert_response :success
  end
end
```

**Comment by mikeborg** [comment]
I'm following your same approach by doing:
    sign_in @user
    get_with @user, :show,{:id=> @user.id}, session #this is where the session from sign_in is added to get_with

However I am in Rails 3.1 and am getting this error:
    Failure/Error: get_with user, action, {:id => id}, session
     NoMethodError:
       private method `stringify_keys' called for #ActionController::TestSession:0x0000010561e080

Any ideas?

**Comment by alvesoaj** [comment]
Some one has any ideas?!
